<?php

namespace crawler\lbccrawlerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends EntityRepository
{
	public function loadAll(){
		$query = $this->getEntityManager()
        			  ->createQuery('
				            SELECT a, i FROM crawlerlbccrawlerBundle:Ad a
				            JOIN a.images i
				            WHERE a.isPublish = 1
				            ORDER BY a.publishedDate DESC'
				        );
		return $query->getResult();
	}
}
